language: php

matrix:
  include:
    - php: 5.3
      dist: precise
      # PHP 5.3 is supported only on Precise.
      # See https://docs.travis-ci.com/user/reference/trusty#PHP-images

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit
